export const lga_list = {
    'Abia': [
        {"label": "Aba North", "value": "Aba North"}, {"label": "Arochukwu", "value": "Arochukwu"}, {"label": "Aba South", "value": "Aba South"}, {"label": "Isiala Ngwa South", "value": "Isiala Ngwa South"}, {"label": "Bende", "value": "Bende"}, {"label": "Ikwuano", "value": "Ikwuano"}, {"label": "Isiala", "value": "Isiala"}, {"label": "Ngwa North", "value": "Ngwa North"}, {"label": "Isukwuato", "value": "Isukwuato"}, {"label": "Ukwa West", "value": "Ukwa West"}, {"label": "Ukwa East", "value": "Ukwa East"}, {"label": "Umuahia South", "value": "Umuahia South"}, {"label": "Umuahia", "value": "Umuahia"}
    ],
    'Adamawa': [
        {"label": "Demsa", "value": "Demsa"}, {"label": "Fufore", "value": "Fufore"}, {"label": "Ganye", "value": "Ganye"}, {"label": "Girei", "value": "Girei"}, {"label": "Gombi", "value": "Gombi"}, {"label": "Jada", "value": "Jada"}, {"label": "Yola North", "value": "Yola North"}, {"label": "Lamurde", "value": "Lamurde"}, {"label": "Madagali", "value": "Madagali"}, {"label": "Maiha", "value": "Maiha"}, {"label": "Mayo-Belwa", "value": "Mayo-Belwa"}, {"label": "Michika", "value": "Michika"}, {"label": "Mubi South", "value": "Mubi South"}, {"label": "Numna", "value": "Numna"}, {"label": "Shelleng", "value": "Shelleng"}, {"label": "Song", "value": "Song"}, {"label": "Toungo", "value": "Toungo"}, {"label": "Jimeta", "value": "Jimeta"}, {"label": "Yola South", "value": "Yola South"}, {"label": "Hung", "value": "Hung"}
    ],
    'Akwa-Ibom': [
        {"label": "Abak", "value": "Abak"}, {"label": "Eastern Obolo", "value": "Eastern Obolo"}, {"label": "Eket", "value": "Eket"}, {"label": "Essien Udim", "value": "Essien Udim"}, {"label": "Etimekpo", "value": "Etimekpo"}, {"label": "Etinan", "value": "Etinan"}, {"label": "Ibeno", "value": "Ibeno"}, {"label": "Ibesikpo Asutan", "value": "Ibesikpo Asutan"}, {"label": "Ibiono Ibom", "value": "Ibiono Ibom"}, {"label": "Ika", "value": "Ika"}, {"label": "Ikono", "value": "Ikono"}, {"label": "Ikot Abasi", "value": "Ikot Abasi"}, {"label": "Ikot Ekpene", "value": "Ikot Ekpene"}, {"label": "Ini", "value": "Ini"}, {"label": "Itu", "value": "Itu"}, {"label": "Mbo", "value": "Mbo"}, {"label": "Mkpat Enin", "value": "Mkpat Enin"}, {"label": "Nsit Ibom", "value": "Nsit Ibom"}, {"label": "Nsit Ubium", "value": "Nsit Ubium"}, {"label": "Obot Akara", "value": "Obot Akara"}, {"label": "Okobo", "value": "Okobo"}, {"label": "Onna", "value": "Onna"}, {"label": "Orukanam", "value": "Orukanam"}, {"label": "Oron", "value": "Oron"}, {"label": "Udung Uko", "value": "Udung Uko"}, {"label": "Ukanafun", "value": "Ukanafun"}, {"label": "Esit Eket", "value": "Esit Eket"}, {"label": "Uruan", "value": "Uruan"}, {"label": "Urue Offoung", "value": "Urue Offoung"}, {"label": "Oruko Ete", "value": "Oruko Ete"}, {"label": "Uyo", "value": "Uyo"}
    ],
    'Anambra': [
        {"label": "Aguata", "value": "Aguata"}, {"label": "Akwa North", "value": "Akwa North"}, {"label": "Anambra", "value": "Anambra"}, {"label": "Anambra-West", "value": "Anambra-West"}, {"label": "Anaocha", "value": "Anaocha"}, {"label": "Awka-North", "value": "Awka-North"}, {"label": "Awka-South", "value": "Awka-South"}, {"label": "Ayamelum", "value": "Ayamelum"}, {"label": "Dunukofia", "value": "Dunukofia"}, {"label": "Ekwusigo", "value": "Ekwusigo"}, {"label": "Idemili-North", "value": "Idemili-North"}, {"label": "Idemili-South", "value": "Idemili-South"}, {"label": "Ihiala", "value": "Ihiala"}, {"label": "Imo", "value": "Imo"}, {"label": "Nibo", "value": "Nibo"}, {"label": "Njikoka", "value": "Njikoka"}, {"label": "Nnewi-North", "value": "Nnewi-North"}, {"label": "Nnewi-South", "value": "Nnewi-South"}, {"label": "Ogbaru", "value": "Ogbaru"}, {"label": "Olumba", "value": "Olumba"}, {"label": "Onitsha-North", "value": "Onitsha-North"}, {"label": "Onitsha-South", "value": "Onitsha-South"}, {"label": "Orumba-North", "value": "Orumba-North"}, {"label": "Orumba-South", "value": "Orumba-South"}, {"label": "Oti", "value": "Oti"}, {"label": "Otu-Ocha", "value": "Otu-Ocha"}, {"label": "Ubuluizor Ihiala", "value": "Ubuluizor Ihiala"}, {"label": "Uyi", "value": "Uyi"}
    ],
    'Bauchi': [
        {"label": "Alkaleri", "value": "Alkaleri"}, {"label": "Bauchi", "value": "Bauchi"}, {"label": "Bogoro", "value": "Bogoro"}, {"label": "Damban", "value": "Damban"}, {"label": "Darazo", "value": "Darazo"}, {"label": "Dass", "value": "Dass"}, {"label": "Gamawa", "value": "Gamawa"}, {"label": "Ganjuwa", "value": "Ganjuwa"}, {"label": "Giade", "value": "Giade"}, {"label": "Itas/Gadau", "value": "Itas/Gadau"}, {"label": "Jama'Are", "value": "Jama'Are"}, {"label": "Katagum", "value": "Katagum"}, {"label": "Kirfi", "value": "Kirfi"}, {"label": "Misau", "value": "Misau"}, {"label": "Ningi", "value": "Ningi"}, {"label": "Shira", "value": "Shira"}, {"label": "Tafawa-Balewa", "value": "Tafawa-Balewa"}, {"label": "Toro", "value": "Toro"}, {"label": "Warji", "value": "Warji"}, {"label": "Zaki", "value": "Zaki"}
    ],
    'rivers': [
        {label: 'Bonny', value: 'bonny'},
        {label: 'Degema', value: 'degema'},
        {label: 'Andoni', value: 'andoni'},
    ],
    'Benue': [
        {"label": "Ado", "value": "Ado"}, {"label": "Agatu", "value": "Agatu"}, {"label": "Apa", "value": "Apa"}, {"label": "Buruku", "value": "Buruku"}, {"label": "Gboko", "value": "Gboko"}, {"label": "Guma", "value": "Guma"}, {"label": "Gwer-East", "value": "Gwer-East"}, {"label": "Gwer-West", "value": "Gwer-West"}, {"label": "Katsina-Ala", "value": "Katsina-Ala"}, {"label": "Konshisha", "value": "Konshisha"}, {"label": "Kwande", "value": "Kwande"}, {"label": "Logo", "value": "Logo"}, {"label": "Makurdi", "value": "Makurdi"}, {"label": "Ogbadibo", "value": "Ogbadibo"}, {"label": "Ohimini", "value": "Ohimini"}, {"label": "Oju", "value": "Oju"}, {"label": "Okpokwu", "value": "Okpokwu"}, {"label": "Otukpo", "value": "Otukpo"}, {"label": "Oturkpa", "value": "Oturkpa"}, {"label": "Tarka", "value": "Tarka"}, {"label": "Ukum", "value": "Ukum"}, {"label": "Vandekya", "value": "Vandekya"}
    ],
    'Borno': [
        {"label": "Abadan", "value": "Abadan"}, {"label": "Askira-Uba", "value": "Askira-Uba"}, {"label": "Bama", "value": "Bama"}, {"label": "Bayo", "value": "Bayo"}, {"label": "Biu", "value": "Biu"}, {"label": "Chibok", "value": "Chibok"}, {"label": "Damboa", "value": "Damboa"}, {"label": "Dikwa", "value": "Dikwa"}, {"label": "Gubio", "value": "Gubio"}, {"label": "Guzamala", "value": "Guzamala"}, {"label": "Gwoza", "value": "Gwoza"}, {"label": "Hawul", "value": "Hawul"}, {"label": "Jere", "value": "Jere"}, {"label": "Kaga", "value": "Kaga"}, {"label": "Kala/Balge", "value": "Kala/Balge"}, {"label": "Konduga", "value": "Konduga"}, {"label": "Kukawa", "value": "Kukawa"}, {"label": "Kwaya-Kusar", "value": "Kwaya-Kusar"}, {"label": "Mafa", "value": "Mafa"}, {"label": "Magumeri", "value": "Magumeri"}, {"label": "Maiduguri", "value": "Maiduguri"}, {"label": "Marte", "value": "Marte"}, {"label": "Mobbar", "value": "Mobbar"}, {"label": "Mongunu", "value": "Mongunu"}, {"label": "Ngala", "value": "Ngala"}, {"label": "Nganzai", "value": "Nganzai"}, {"label": "Shani", "value": "Shani"}
    ],
    'Bayelsa': [
        {"label": "Adagbabiri", "value": "Adagbabiri"}, {"label": "Brass", "value": "Brass"}, {"label": "Ekeremor", "value": "Ekeremor"}, {"label": "Kembe", "value": "Kembe"}, {"label": "Kolokuma", "value": "Kolokuma"}, {"label": "Kolokuma/Opkuma", "value": "Kolokuma/Opkuma"}, {"label": "Nembe", "value": "Nembe"}, {"label": "Ogbia", "value": "Ogbia"}, {"label": "Sagbama", "value": "Sagbama"}, {"label": "Southern-Ijaw", "value": "Southern-Ijaw"}, {"label": "Toru-Abubo", "value": "Toru-Abubo"}, {"label": "Yenegoa", "value": "Yenegoa"}
    ],
    'Cross-River': [
        {"label": "Abi", "value": "Abi"}, {"label": "Abuochichie", "value": "Abuochichie"}, {"label": "Akamkpa", "value": "Akamkpa"}, {"label": "Akpabuyo", "value": "Akpabuyo"}, {"label": "Bakassi", "value": "Bakassi"}, {"label": "Bekwara", "value": "Bekwara"}, {"label": "Biasi", "value": "Biasi"}, {"label": "Boki", "value": "Boki"}, {"label": "Calabar-Municipal", "value": "Calabar-Municipal"}, {"label": "Calabar-South", "value": "Calabar-South"}, {"label": "Etunk", "value": "Etunk"}, {"label": "Ikom", "value": "Ikom"}, {"label": "Obanliku", "value": "Obanliku"}, {"label": "Obubra", "value": "Obubra"}, {"label": "Obudu", "value": "Obudu"}, {"label": "Odukpani", "value": "Odukpani"}, {"label": "Ogoja", "value": "Ogoja"}, {"label": "Ugep-North", "value": "Ugep-North"}, {"label": "Yakurr", "value": "Yakurr"}, {"label": "Yala", "value": "Yala"}
    ],
    'Delta': [
        {"label": "Aniocha North", "value": "Aniocha North"}, {"label": "Aniocha-North", "value": "Aniocha-North"}, {"label": "Aniocha-South", "value": "Aniocha-South"}, {"label": "Bomadi", "value": "Bomadi"}, {"label": "Burutu", "value": "Burutu"}, {"label": "Effurun", "value": "Effurun"}, {"label": "Ethiope-East", "value": "Ethiope-East"}, {"label": "Ethiope-West", "value": "Ethiope-West"}, {"label": "Idu", "value": "Idu"}, {"label": "Ika-Ne", "value": "Ika-Ne"}, {"label": "Ika-North-East", "value": "Ika-North-East"}, {"label": "Ika-South", "value": "Ika-South"}, {"label": "Ikpemili", "value": "Ikpemili"}, {"label": "Isoko-North", "value": "Isoko-North"}, {"label": "Isoko-South", "value": "Isoko-South"}, {"label": "Ndokwa-East", "value": "Ndokwa-East"}, {"label": "Ndokwa-North", "value": "Ndokwa-North"}, {"label": "Ndokwa-South", "value": "Ndokwa-South"}, {"label": "Ndokwa-West", "value": "Ndokwa-West"}, {"label": "Okpe", "value": "Okpe"}, {"label": "Okwuani", "value": "Okwuani"}, {"label": "Oleh", "value": "Oleh"}, {"label": "Oshielli-North", "value": "Oshielli-North"}, {"label": "Oshimili", "value": "Oshimili"}, {"label": "Oshimili-North", "value": "Oshimili-North"}, {"label": "Oshimili-South", "value": "Oshimili-South"}, {"label": "Osimili", "value": "Osimili"}, {"label": "Osimili-North", "value": "Osimili-North"}, {"label": "Osimili-South", "value": "Osimili-South"}, {"label": "Patani", "value": "Patani"}, {"label": "Sapele", "value": "Sapele"}, {"label": "Udokwa", "value": "Udokwa"}, {"label": "Udu", "value": "Udu"}, {"label": "Ughelli-North", "value": "Ughelli-North"}, {"label": "Ughelli-South", "value": "Ughelli-South"}, {"label": "Ukwuani", "value": "Ukwuani"}, {"label": "Uraun", "value": "Uraun"}, {"label": "Urwie", "value": "Urwie"}, {"label": "Uvie", "value": "Uvie"}, {"label": "Uvwei", "value": "Uvwei"}, {"label": "Uvwie", "value": "Uvwie"}, {"label": "Uwvie", "value": "Uwvie"}, {"label": "Warri-Central", "value": "Warri-Central"}, {"label": "Warri-North", "value": "Warri-North"}, {"label": "Warri-South", "value": "Warri-South"}
    ],
    'Ebonyi': [
        {"label": "Abakaliki", "value": "Abakaliki"}, {"label": "Afikpo-North", "value": "Afikpo-North"}, {"label": "Afikpo-South", "value": "Afikpo-South"}, {"label": "Bomadim", "value": "Bomadim"}, {"label": "Ebonyi", "value": "Ebonyi"}, {"label": "Ezza-North", "value": "Ezza-North"}, {"label": "Ezza-South", "value": "Ezza-South"}, {"label": "Ikwo", "value": "Ikwo"}, {"label": "Ishielu", "value": "Ishielu"}, {"label": "Ivo", "value": "Ivo"}, {"label": "Izzi", "value": "Izzi"}, {"label": "Obaukwu", "value": "Obaukwu"}, {"label": "Ohakwu", "value": "Ohakwu"}, {"label": "Onicha", "value": "Onicha"}, {"label": "Ukaba", "value": "Ukaba"}
    ],
    'Edo': [
        {"label": "Afokpella", "value": "Afokpella"}, {"label": "Afuze", "value": "Afuze"}, {"label": "Agbazilo", "value": "Agbazilo"}, {"label": "Akoko Edo", "value": "Akoko Edo"}, {"label": "Akoko-Edo", "value": "Akoko-Edo"}, {"label": "Egor", "value": "Egor"}, {"label": "Esan-Central", "value": "Esan-Central"}, {"label": "Esan-North-East", "value": "Esan-North-East"}, {"label": "Esan-North-East", "value": "Esan-North-East"}, {"label": "Esan-South-East", "value": "Esan-South-East"}, {"label": "Esan-West", "value": "Esan-West"}, {"label": "Etsako-Central", "value": "Etsako-Central"}, {"label": "Etsako-East", "value": "Etsako-East"}, {"label": "Etsako-West", "value": "Etsako-West"}, {"label": "Igueben", "value": "Igueben"}, {"label": "Iguobano North East", "value": "Iguobano North East"}, {"label": "Ikpoba-Okha", "value": "Ikpoba-Okha"}, {"label": "Ohunmwode", "value": "Ohunmwode"}, {"label": "Ologbo", "value": "Ologbo"}, {"label": "Opoji Irrua", "value": "Opoji Irrua"}, {"label": "Opoji Irrua", "value": "Opoji Irrua"}, {"label": "Oredo", "value": "Oredo"}, {"label": "Orhionmwon", "value": "Orhionmwon"}, {"label": "Ovia-North-East", "value": "Ovia-North-East"}, {"label": "Ovia-South-West", "value": "Ovia-South-West"}, {"label": "Owan East", "value": "Owan East"}, {"label": "Owan-East", "value": "Owan-East"}, {"label": "Owan-West", "value": "Owan-West"}, {"label": "Uhunmwonde", "value": "Uhunmwonde"}
    ],
    'Ekiti': [
        {"label": "Ado-Ekiti", "value": "Ado-Ekiti"}, {"label": "Aiyekire", "value": "Aiyekire"}, {"label": "Efon", "value": "Efon"}, {"label": "Ekiti-East", "value": "Ekiti-East"}, {"label": "Ekiti-South-West", "value": "Ekiti-South-West"}, {"label": "Ekiti-West", "value": "Ekiti-West"}, {"label": "Emure/Ise/Orun", "value": "Emure/Ise/Orun"}, {"label": "Gbonyin", "value": "Gbonyin"}, {"label": "Ido-Osi", "value": "Ido-Osi"}, {"label": "Ijero", "value": "Ijero"}, {"label": "Ikare", "value": "Ikare"}, {"label": "Ikere", "value": "Ikere"}, {"label": "Ikole", "value": "Ikole"}, {"label": "Ilejemeje", "value": "Ilejemeje"}, {"label": "Irepodun/Ifelodun", "value": "Irepodun/Ifelodun"}, {"label": "Ise-Orun", "value": "Ise-Orun"}, {"label": "Moba", "value": "Moba"}, {"label": "Oye", "value": "Oye"}
    ],
    'Enugu': [
       {"label": "Aninri", "value": "Aninri"}, {"label": "Awgu", "value": "Awgu"}, {"label": "Enugu-East", "value": "Enugu-East"}, {"label": "Enugu-North", "value": "Enugu-North"}, {"label": "Enugu-South", "value": "Enugu-South"}, {"label": "Ezeagu", "value": "Ezeagu"}, {"label": "Igbo-Etiti", "value": "Igbo-Etiti"}, {"label": "Igbo-Eze-North", "value": "Igbo-Eze-North"}, {"label": "Igbo-Eze-South", "value": "Igbo-Eze-South"}, {"label": "Isi-Uzo", "value": "Isi-Uzo"}, {"label": "Nkanu-East", "value": "Nkanu-East"}, {"label": "Nkanu-West", "value": "Nkanu-West"}, {"label": "Nsukka", "value": "Nsukka"}, {"label": "Nukanu East", "value": "Nukanu East"}, {"label": "Oji-River", "value": "Oji-River"}, {"label": "Udenu", "value": "Udenu"}, {"label": "Udi", "value": "Udi"}, {"label": "Uzo-Uwani", "value": "Uzo-Uwani"}
    ],
    'FCT': [
        {"label": "Abaji", "value": "Abaji"}, {"label": "Abuja Municipal", "value": "Abuja Municipal"}, {"label": "Gwagwalada", "value": "Gwagwalada"}, {"label": "Kuje", "value": "Kuje"}, {"label": "Bwari", "value": "Bwari"}, {"label": "Kwali", "value": "Kwali"}
    ],
    'Gombe': [
        {"label": "Akko", "value": "Akko"}, {"label": "Balanga", "value": "Balanga"}, {"label": "Billiri", "value": "Billiri"}, {"label": "Dukku", "value": "Dukku"}, {"label": "Funakaye", "value": "Funakaye"}, {"label": "Gombe", "value": "Gombe"}, {"label": "Kaltungo", "value": "Kaltungo"}, {"label": "Kwami", "value": "Kwami"}, {"label": "Nafada/Bajoga", "value": "Nafada/Bajoga"}, {"label": "Shomgom", "value": "Shomgom"}, {"label": "Yamaltu/Deba", "value": "Yamaltu/Deba"}
    ],
    'Imo': [
        {"label": "Aboh-Mbaise", "value": "Aboh-Mbaise"}, {"label": "Ahiazu-Mbaise", "value": "Ahiazu-Mbaise"}, {"label": "Dral-Esat", "value": "Dral-Esat"}, {"label": "Ehime-Mbano", "value": "Ehime-Mbano"}, {"label": "Ezeobodo", "value": "Ezeobodo"}, {"label": "Ezinihitte", "value": "Ezinihitte"}, {"label": "Ideato", "value": "Ideato"}, {"label": "Ideato-North", "value": "Ideato-North"}, {"label": "Ideato-South", "value": "Ideato-South"}, {"label": "Ihitte/Uboma", "value": "Ihitte/Uboma"}, {"label": "Ikeduru", "value": "Ikeduru"}, {"label": "Isiala-Mbano", "value": "Isiala-Mbano"}, {"label": "Isu", "value": "Isu"}, {"label": "Mbaitoli", "value": "Mbaitoli"}, {"label": "Mbano", "value": "Mbano"}, {"label": "Ngor-Okpala", "value": "Ngor-Okpala"}, {"label": "Njaba", "value": "Njaba"}, {"label": "Nkwerre", "value": "Nkwerre"}, {"label": "Nwangele", "value": "Nwangele"}, {"label": "Obowo", "value": "Obowo"}, {"label": "Oguta", "value": "Oguta"}, {"label": "Ohaji-Egbema", "value": "Ohaji-Egbema"}, {"label": "Okigwe", "value": "Okigwe"}, {"label": "Onuimo", "value": "Onuimo"}, {"label": "Orlu", "value": "Orlu"}, {"label": "Oro-West", "value": "Oro-West"}, {"label": "Orsu", "value": "Orsu"}, {"label": "Oru-East", "value": "Oru-East"}, {"label": "Oru-West", "value": "Oru-West"}, {"label": "Owerri-Municipal", "value": "Owerri-Municipal"}, {"label": "Owerri-North", "value": "Owerri-North"}, {"label": "Owerri-West", "value": "Owerri-West"}, {"label": "Ugiri-Ike Ikeduru", "value": "Ugiri-Ike Ikeduru"}, {"label": "Ugiri-Ikedikeduru", "value": "Ugiri-Ikedikeduru"}, {"label": "Unbano", "value": "Unbano"}, {"label": "Zinihitte", "value": "Zinihitte"}
    ],
    'Jigawa': [
        {"label": "Auyo", "value": "Auyo"}, {"label": "Babura", "value": "Babura"}, {"label": "Biriniwa", "value": "Biriniwa"}, {"label": "Birnin-Kudu", "value": "Birnin-Kudu"}, {"label": "Bosuwa", "value": "Bosuwa"}, {"label": "Buji", "value": "Buji"}, {"label": "Dutse", "value": "Dutse"}, {"label": "Gagarawa", "value": "Gagarawa"}, {"label": "Garki", "value": "Garki"}, {"label": "Gumel", "value": "Gumel"}, {"label": "Guri", "value": "Guri"}, {"label": "Gwaram", "value": "Gwaram"}, {"label": "Gwiwa", "value": "Gwiwa"}, {"label": "Hadejia", "value": "Hadejia"}, {"label": "Jahun", "value": "Jahun"}, {"label": "Kafin-Hausa", "value": "Kafin-Hausa"}, {"label": "Kaugama", "value": "Kaugama"}, {"label": "Kazaure", "value": "Kazaure"}, {"label": "Kirkasamma", "value": "Kirkasamma"}, {"label": "Maigatari", "value": "Maigatari"}, {"label": "Malam-Maduri", "value": "Malam-Maduri"}, {"label": "Miga", "value": "Miga"}, {"label": "Ringim", "value": "Ringim"}, {"label": "Roni", "value": "Roni"}, {"label": "Sule-Tankarkar", "value": "Sule-Tankarkar"}, {"label": "Taura", "value": "Taura"}, {"label": "Yankwashi", "value": "Yankwashi"}
    ],
    'Kebbi': [
        {"label": "Aleiro", "value": "Aleiro"}, {"label": "Arewa-Dandi", "value": "Arewa-Dandi"}, {"label": "Argungu", "value": "Argungu"}, {"label": "Augie", "value": "Augie"}, {"label": "Bagudo", "value": "Bagudo"}, {"label": "Birnin-Kebbi", "value": "Birnin-Kebbi"}, {"label": "Bumza", "value": "Bumza"}, {"label": "Dandi", "value": "Dandi"}, {"label": "Danko", "value": "Danko"}, {"label": "Fakai", "value": "Fakai"}, {"label": "Gwandu", "value": "Gwandu"}, {"label": "Jega", "value": "Jega"}, {"label": "Kalgo", "value": "Kalgo"}, {"label": "Koko-Besse", "value": "Koko-Besse"}, {"label": "Maiyama", "value": "Maiyama"}, {"label": "Ngaski", "value": "Ngaski"}, {"label": "Sakaba", "value": "Sakaba"}, {"label": "Shanga", "value": "Shanga"}, {"label": "Suru", "value": "Suru"}, {"label": "Wasagu", "value": "Wasagu"}, {"label": "Yauri", "value": "Yauri"}, {"label": "Zuru", "value": "Zuru"}
    ],
    'Kaduna': [
        {"label": "Birnin-Gwari", "value": "Birnin-Gwari"}, {"label": "Chikun", "value": "Chikun"}, {"label": "Giwa", "value": "Giwa"}, {"label": "Gwagwada", "value": "Gwagwada"}, {"label": "Igabi", "value": "Igabi"}, {"label": "Ikara", "value": "Ikara"}, {"label": "Jaba", "value": "Jaba"}, {"label": "Jema'A", "value": "Jema'A"}, {"label": "Kachia", "value": "Kachia"}, {"label": "Kaduna-North", "value": "Kaduna-North"}, {"label": "Kagarko", "value": "Kagarko"}, {"label": "Kajuru", "value": "Kajuru"}, {"label": "Kaura", "value": "Kaura"}, {"label": "Kauru", "value": "Kauru"}, {"label": "Koka/Kawo", "value": "Koka/Kawo"}, {"label": "Kubah", "value": "Kubah"}, {"label": "Kudan", "value": "Kudan"}, {"label": "Lere", "value": "Lere"}, {"label": "Makarfi", "value": "Makarfi"}, {"label": "Sabon-Gari", "value": "Sabon-Gari"}, {"label": "Sanga", "value": "Sanga"}, {"label": "Soba", "value": "Soba"}, {"label": "Tudun-Wada/Makera", "value": "Tudun-Wada/Makera"}, {"label": "Zango-Kataf", "value": "Zango-Kataf"}, {"label": "Zaria", "value": "Zaria"}
    ],
    'Kano': [
        {"label": "Ajingi", "value": "Ajingi"}, {"label": "Albasu", "value": "Albasu"}, {"label": "Bagwai", "value": "Bagwai"}, {"label": "Bebeji", "value": "Bebeji"}, {"label": "Bichi", "value": "Bichi"}, {"label": "Bunkure", "value": "Bunkure"}, {"label": "Dala", "value": "Dala"}, {"label": "Dambatta", "value": "Dambatta"}, {"label": "Dawakin-Kudu", "value": "Dawakin-Kudu"}, {"label": "Dawakin-Tofa", "value": "Dawakin-Tofa"}, {"label": "Doguwa", "value": "Doguwa"}, {"label": "Fagge", "value": "Fagge"}, {"label": "Gabasawa", "value": "Gabasawa"}, {"label": "Garko", "value": "Garko"}, {"label": "Garun-Mallam", "value": "Garun-Mallam"}, {"label": "Gaya", "value": "Gaya"}, {"label": "Gezawa", "value": "Gezawa"}, {"label": "Gwale", "value": "Gwale"}, {"label": "Gwarzo", "value": "Gwarzo"}, {"label": "Kano-Municipal", "value": "Kano-Municipal"}, {"label": "Karaye", "value": "Karaye"}, {"label": "Kibiya", "value": "Kibiya"}, {"label": "Kiru", "value": "Kiru"}, {"label": "Kumbotso", "value": "Kumbotso"}, {"label": "Kunchi", "value": "Kunchi"}, {"label": "Kura", "value": "Kura"}, {"label": "Madobi", "value": "Madobi"}, {"label": "Makoda", "value": "Makoda"}, {"label": "Minjibir", "value": "Minjibir"}, {"label": "Nasarawa", "value": "Nasarawa"}, {"label": "Rano", "value": "Rano"}, {"label": "Rimin-Gado", "value": "Rimin-Gado"}, {"label": "Rogo", "value": "Rogo"}, {"label": "Shanono", "value": "Shanono"}, {"label": "Sumaila", "value": "Sumaila"}, {"label": "Takai", "value": "Takai"}, {"label": "Tarauni", "value": "Tarauni"}, {"label": "Tofa", "value": "Tofa"}, {"label": "Tsanyawa", "value": "Tsanyawa"}, {"label": "Tudun-Wada", "value": "Tudun-Wada"}, {"label": "Ungogo", "value": "Ungogo"}, {"label": "Warawa", "value": "Warawa"}, {"label": "Wudil", "value": "Wudil"}
    ],
    'Kogi': [
        {"label": "Adavi", "value": "Adavi"}, {"label": "Ajaokuta", "value": "Ajaokuta"}, {"label": "Ankpa", "value": "Ankpa"}, {"label": "Dekina", "value": "Dekina"}, {"label": "Ibaji", "value": "Ibaji"}, {"label": "Idah", "value": "Idah"}, {"label": "Igalamela", "value": "Igalamela"}, {"label": "Ijumu", "value": "Ijumu"}, {"label": "Ikoyi-Ijumu", "value": "Ikoyi-Ijumu"}, {"label": "Kabba/Bunu", "value": "Kabba/Bunu"}, {"label": "Kogi", "value": "Kogi"}, {"label": "Lokoja", "value": "Lokoja"}, {"label": "Mopa-Muro-Mopi", "value": "Mopa-Muro-Mopi"}, {"label": "Obaji", "value": "Obaji"}, {"label": "Ofu", "value": "Ofu"}, {"label": "Ogori/Magongo", "value": "Ogori/Magongo"}, {"label": "Okehi", "value": "Okehi"}, {"label": "Okene", "value": "Okene"}, {"label": "Olamaboro", "value": "Olamaboro"}, {"label": "Omala", "value": "Omala"}, {"label": "Oru", "value": "Oru"}, {"label": "Oyi", "value": "Oyi"}, {"label": "Yagba-East", "value": "Yagba-East"}, {"label": "Yagba-West", "value": "Yagba-West"}
    ],
    'Katsina': [
        {"label": "Bakori", "value": "Bakori"}, {"label": "Batagarawa", "value": "Batagarawa"}, {"label": "Batsari", "value": "Batsari"}, {"label": "Baure", "value": "Baure"}, {"label": "Bindawa", "value": "Bindawa"}, {"label": "Charanchi", "value": "Charanchi"}, {"label": "Dan-Musa", "value": "Dan-Musa"}, {"label": "Dandume", "value": "Dandume"}, {"label": "Danji", "value": "Danji"}, {"label": "Daura", "value": "Daura"}, {"label": "Dutsi", "value": "Dutsi"}, {"label": "Dutsinma", "value": "Dutsinma"}, {"label": "Faskari", "value": "Faskari"}, {"label": "Funtua", "value": "Funtua"}, {"label": "Ingawa", "value": "Ingawa"}, {"label": "Jibia", "value": "Jibia"}, {"label": "Kafur", "value": "Kafur"}, {"label": "Kaita", "value": "Kaita"}, {"label": "Kankara", "value": "Kankara"}, {"label": "Kankia", "value": "Kankia"}, {"label": "Katsina", "value": "Katsina"}, {"label": "Kurfi", "value": "Kurfi"}, {"label": "Kusada", "value": "Kusada"}, {"label": "Mai-Adua", "value": "Mai-Adua"}, {"label": "Malumfashi", "value": "Malumfashi"}, {"label": "Mani", "value": "Mani"}, {"label": "Mashi", "value": "Mashi"}, {"label": "Matazu", "value": "Matazu"}, {"label": "Musawa", "value": "Musawa"}, {"label": "Rimi", "value": "Rimi"}, {"label": "Sabuwa", "value": "Sabuwa"}, {"label": "Safana", "value": "Safana"}, {"label": "Sandamu", "value": "Sandamu"}, {"label": "Zango", "value": "Zango"}
    ],
    'Kwara': [
        {"label": "Asa", "value": "Asa"}, {"label": "Baruten", "value": "Baruten"}, {"label": "Edu", "value": "Edu"}, {"label": "Ekiti", "value": "Ekiti"}, {"label": "Ifelodun", "value": "Ifelodun"}, {"label": "Ilorin south", "value": "Ilorin south"}, {"label": "Ilorin west", "value": "Ilorin west"}, {"label": "Ilorin east", "value": "Ilorin east"}, {"label": "Irepodun", "value": "Irepodun"}, {"label": "Isin", "value": "Isin"}, {"label": "Kaiama", "value": "Kaiama"}, {"label": "Moro", "value": "Moro"}, {"label": "Offa", "value": "Offa"}, {"label": "Oke ero", "value": "Oke ero"}, {"label": "Oyun", "value": "Oyun"}, {"label": "Pategi", "value": "Pategi"}
    ],
    'Lagos': [
        {"label": "Agege", "value": "Agege"}, {"label": "Ajeromi-Ifelodun", "value": "Ajeromi-Ifelodun"}, {"label": "Alimosho", "value": "Alimosho"}, {"label": "Amuwo-Odofin", "value": "Amuwo-Odofin"}, {"label": "Apapa", "value": "Apapa"}, {"label": "Badagry", "value": "Badagry"}, {"label": "Epe", "value": "Epe"}, {"label": "Eti-Osa", "value": "Eti-Osa"}, {"label": "Ibeju-Lekki", "value": "Ibeju-Lekki"}, {"label": "Ifako-Ijaiye", "value": "Ifako-Ijaiye"}, {"label": "Ikeja", "value": "Ikeja"}, {"label": "Ikorodu", "value": "Ikorodu"}, {"label": "Kosofe", "value": "Kosofe"}, {"label": "Lagos-Island", "value": "Lagos-Island"}, {"label": "Lagos-Mainland", "value": "Lagos-Mainland"}, {"label": "Mushin", "value": "Mushin"}, {"label": "Ojo", "value": "Ojo"}, {"label": "Oshodi-Isolo", "value": "Oshodi-Isolo"}, {"label": "Shomolu", "value": "Shomolu"}, {"label": "Somolu", "value": "Somolu"}, {"label": "Surulere", "value": "Surulere"}
    ],
    'Nassarawa': [
        {"label": "Akwanga", "value": "Akwanga"}, {"label": "Awe", "value": "Awe"}, {"label": "Doma", "value": "Doma"}, {"label": "Karu", "value": "Karu"}, {"label": "Keana", "value": "Keana"}, {"label": "Keffi", "value": "Keffi"}, {"label": "Kokona", "value": "Kokona"}, {"label": "Lafia", "value": "Lafia"}, {"label": "Nassawara", "value": "Nassawara"}, {"label": "Nassawara Eggon", "value": "Nassawara Eggon"}, {"label": "Obi", "value": "Obi"}, {"label": "Wambu", "value": "Wambu"}
    ],
    'Niger': [
        {"label": "Agaie", "value": "Agaie"}, {"label": "Agwara", "value": "Agwara"}, {"label": "Bida", "value": "Bida"}, {"label": "Borgu", "value": "Borgu"}, {"label": "Bosso", "value": "Bosso"}, {"label": "Chanchaga", "value": "Chanchaga"}, {"label": "Edati", "value": "Edati"}, {"label": "Gbako", "value": "Gbako"}, {"label": "Gurara", "value": "Gurara"}, {"label": "Katcha", "value": "Katcha"}, {"label": "Kontagora", "value": "Kontagora"}, {"label": "Lapai", "value": "Lapai"}, {"label": "Lavun", "value": "Lavun"}, {"label": "Magama", "value": "Magama"}, {"label": "Mariga", "value": "Mariga"}, {"label": "Mashegu", "value": "Mashegu"}, {"label": "Mokwa", "value": "Mokwa"}, {"label": "Muya", "value": "Muya"}, {"label": "Paikoro", "value": "Paikoro"}, {"label": "Rafi", "value": "Rafi"}, {"label": "Rijau", "value": "Rijau"}, {"label": "Shiroro", "value": "Shiroro"}, {"label": "Suleja", "value": "Suleja"}, {"label": "Tafa", "value": "Tafa"}, {"label": "Wushishi", "value": "Wushishi"}
    ],
    'Ogun': [
        {"label": "Abeokuta-North", "value": "Abeokuta-North"}, {"label": "Abeokuta-South", "value": "Abeokuta-South"}, {"label": "Ado-Odo/Ota", "value": "Ado-Odo/Ota"}, {"label": "Ewekoro", "value": "Ewekoro"}, {"label": "Ifo", "value": "Ifo"}, {"label": "Ijebu-East", "value": "Ijebu-East"}, {"label": "Ijebu-North", "value": "Ijebu-North"}, {"label": "Ijebu-North-East", "value": "Ijebu-North-East"}, {"label": "Ijebu-Ode", "value": "Ijebu-Ode"}, {"label": "Ikenne", "value": "Ikenne"}, {"label": "Imeko-Afon", "value": "Imeko-Afon"}, {"label": "Ipokia", "value": "Ipokia"}, {"label": "Obafemi-Owode", "value": "Obafemi-Owode"}, {"label": "Odeda", "value": "Odeda"}, {"label": "Odogbolu", "value": "Odogbolu"}, {"label": "Ogun-Waterside", "value": "Ogun-Waterside"}, {"label": "Remo-North", "value": "Remo-North"}, {"label": "Sagamu", "value": "Sagamu"}, {"label": "Yewa North", "value": "Yewa North"}, {"label": "Yewa South", "value": "Yewa South"}
    ],
    'Ondo': [
        {"label": "Akoko", "value": "Akoko"}, {"label": "Akoko-North", "value": "Akoko-North"}, {"label": "Akoko-North-West", "value": "Akoko-North-West"}, {"label": "Akoko-South", "value": "Akoko-South"}, {"label": "Akoko-South-East", "value": "Akoko-South-East"}, {"label": "Akure", "value": "Akure"}, {"label": "Akure-North", "value": "Akure-North"}, {"label": "Akure-South", "value": "Akure-South"}, {"label": "Ese-Odo", "value": "Ese-Odo"}, {"label": "Idanre", "value": "Idanre"}, {"label": "Ifedore", "value": "Ifedore"}, {"label": "Igbisin", "value": "Igbisin"}, {"label": "Ikale", "value": "Ikale"}, {"label": "Ilaje", "value": "Ilaje"}, {"label": "Ilaje-West", "value": "Ilaje-West"}, {"label": "Ile-Oluji-Okeigbo", "value": "Ile-Oluji-Okeigbo"}, {"label": "Irele", "value": "Irele"}, {"label": "Odigbo", "value": "Odigbo"}, {"label": "Oka Ak0Ko", "value": "Oka Ak0Ko"}, {"label": "Okiti Pupa Ijuodo", "value": "Okiti Pupa Ijuodo"}, {"label": "Okiti-Pupa", "value": "Okiti-Pupa"}, {"label": "Ondo", "value": "Ondo"}, {"label": "Ondo West", "value": "Ondo West"}, {"label": "Ondo-East", "value": "Ondo-East"}, {"label": "Ose", "value": "Ose"}, {"label": "Owo", "value": "Owo"}
    ],
    'Osun': [
        {"label": "Atakumosa", "value": "Atakumosa"}, {"label": "Atakumosa East", "value": "Atakumosa East"}, {"label": "Ayeda-Ade", "value": "Ayeda-Ade"}, {"label": "Ayedire", "value": "Ayedire"}, {"label": "Boluwaduro", "value": "Boluwaduro"}, {"label": "Boripe", "value": "Boripe"}, {"label": "Ede", "value": "Ede"}, {"label": "Ede North", "value": "Ede North"}, {"label": "Egbedore", "value": "Egbedore"}, {"label": "Ejigbo", "value": "Ejigbo"}, {"label": "Ife", "value": "Ife"}, {"label": "Ife North", "value": "Ife North"}, {"label": "Ife South", "value": "Ife South"}, {"label": "Ife-Central", "value": "Ife-Central"}, {"label": "Ife-East", "value": "Ife-East"}, {"label": "Ifelodun", "value": "Ifelodun"}, {"label": "Ila", "value": "Ila"}, {"label": "Ilesa-East", "value": "Ilesa-East"}, {"label": "Ilesa-West", "value": "Ilesa-West"}, {"label": "Ilesha", "value": "Ilesha"}, {"label": "Ilesha West", "value": "Ilesha West"}, {"label": "Irepodun", "value": "Irepodun"}, {"label": "Irewole", "value": "Irewole"}, {"label": "Isokan", "value": "Isokan"}, {"label": "Iwo", "value": "Iwo"}, {"label": "Obokun", "value": "Obokun"}, {"label": "Odo-Otin", "value": "Odo-Otin"}, {"label": "Ola Oluwa", "value": "Ola Oluwa"}, {"label": "Olorunda", "value": "Olorunda"}, {"label": "Ori-Ade", "value": "Ori-Ade"}, {"label": "Orolu", "value": "Orolu"}, {"label": "Osogbo", "value": "Osogbo"}
    ],
    'Oyo': [
        {"label": "Afijio", "value": "Afijio"}, {"label": "Akinyele", "value": "Akinyele"}, {"label": "Atiba", "value": "Atiba"}, {"label": "Atisbo", "value": "Atisbo"}, {"label": "Egbeda", "value": "Egbeda"}, {"label": "Ibadan-Central", "value": "Ibadan-Central"}, {"label": "Ibadan-North-East", "value": "Ibadan-North-East"}, {"label": "Ibadan-North-West", "value": "Ibadan-North-West"}, {"label": "Ibadan-South-East", "value": "Ibadan-South-East"}, {"label": "Ibadan-South-West", "value": "Ibadan-South-West"}, {"label": "Ibarapa-Central", "value": "Ibarapa-Central"}, {"label": "Ibarapa-East", "value": "Ibarapa-East"}, {"label": "Ibarapa-North", "value": "Ibarapa-North"}, {"label": "Ido", "value": "Ido"}, {"label": "Irepo", "value": "Irepo"}, {"label": "Iseyin", "value": "Iseyin"}, {"label": "Itseiwaju", "value": "Itseiwaju"}, {"label": "Iwajowa", "value": "Iwajowa"}, {"label": "Kajola", "value": "Kajola"}, {"label": "Lagelu", "value": "Lagelu"}, {"label": "Odo-Oluwa", "value": "Odo-Oluwa"}, {"label": "Ogbomosho-North", "value": "Ogbomosho-North"}, {"label": "Ogbomosho-South", "value": "Ogbomosho-South"}, {"label": "Olorunsogo", "value": "Olorunsogo"}, {"label": "Oluyole", "value": "Oluyole"}, {"label": "Ona-Ara", "value": "Ona-Ara"}, {"label": "Orelope", "value": "Orelope"}, {"label": "Ori-Ire", "value": "Ori-Ire"}, {"label": "Oyo-East", "value": "Oyo-East"}, {"label": "Oyo-West", "value": "Oyo-West"}, {"label": "Saki-East", "value": "Saki-East"}, {"label": "Saki-West", "value": "Saki-West"}, {"label": "Surulere", "value": "Surulere"}
    ],
    'Plateau': [
        {"label": "Barkin-Ladi", "value": "Barkin-Ladi"}, {"label": "Bassa", "value": "Bassa"}, {"label": "Bokkos", "value": "Bokkos"}, {"label": "Jos-East", "value": "Jos-East"}, {"label": "Jos-North", "value": "Jos-North"}, {"label": "Jos-South", "value": "Jos-South"}, {"label": "Kanam", "value": "Kanam"}, {"label": "Kanke", "value": "Kanke"}, {"label": "Langtang-North", "value": "Langtang-North"}, {"label": "Langtang-South", "value": "Langtang-South"}, {"label": "Mangu", "value": "Mangu"}, {"label": "Mikang", "value": "Mikang"}, {"label": "Pankshin", "value": "Pankshin"}, {"label": "Quan'Anpan", "value": "Quan'Anpan"}, {"label": "Riyom", "value": "Riyom"}, {"label": "Shendam", "value": "Shendam"}, {"label": "Wase", "value": "Wase"}
    ],
    'Rivers': [
        {"label": "Aboa/Odual", "value": "Aboa/Odual"}, {"label": "Ahoada-East", "value": "Ahoada-East"}, {"label": "Ahoada-West", "value": "Ahoada-West"}, {"label": "Akukutoru", "value": "Akukutoru"}, {"label": "Andoni", "value": "Andoni"}, {"label": "Asari-Toru", "value": "Asari-Toru"}, {"label": "Bonny", "value": "Bonny"}, {"label": "Buguma", "value": "Buguma"}, {"label": "Degema", "value": "Degema"}, {"label": "Eleme", "value": "Eleme"}, {"label": "Elfane", "value": "Elfane"}, {"label": "Emuoha", "value": "Emuoha"}, {"label": "Etche", "value": "Etche"}, {"label": "Gokana", "value": "Gokana"}, {"label": "Ikwerre", "value": "Ikwerre"}, {"label": "Khana", "value": "Khana"}, {"label": "Obia/Akpor", "value": "Obia/Akpor"}, {"label": "Ogba-Egbema-Ndoni", "value": "Ogba-Egbema-Ndoni"}, {"label": "Ogba/Egbema/Ndoni", "value": "Ogba/Egbema/Ndoni"}, {"label": "Ogu/Bolo", "value": "Ogu/Bolo"}, {"label": "Okirika", "value": "Okirika"}, {"label": "Omuma", "value": "Omuma"}, {"label": "Opobo/Nkoro", "value": "Opobo/Nkoro"}, {"label": "Oyigbo", "value": "Oyigbo"}, {"label": "Port-Harcourt", "value": "Port-Harcourt"}, {"label": "Tai", "value": "Tai"}
    ],
    'Sokoto': [
        {"label": "Binji", "value": "Binji"}, {"label": "Bodinga", "value": "Bodinga"}, {"label": "Dange-Shuni", "value": "Dange-Shuni"}, {"label": "Gada", "value": "Gada"}, {"label": "Goronyo", "value": "Goronyo"}, {"label": "Gudu", "value": "Gudu"}, {"label": "Gwadabawa", "value": "Gwadabawa"}, {"label": "Illela", "value": "Illela"}, {"label": "Kebbe", "value": "Kebbe"}, {"label": "Kware", "value": "Kware"}, {"label": "Raba", "value": "Raba"}, {"label": "Sabo-Birni", "value": "Sabo-Birni"}, {"label": "Shagari", "value": "Shagari"}, {"label": "Silame", "value": "Silame"}, {"label": "Sokoto-North", "value": "Sokoto-North"}, {"label": "Sokoto-South", "value": "Sokoto-South"}, {"label": "Tambuwal", "value": "Tambuwal"}, {"label": "Tangaza", "value": "Tangaza"}, {"label": "Tureta", "value": "Tureta"}, {"label": "Wamakko", "value": "Wamakko"}, {"label": "Wurno", "value": "Wurno"}, {"label": "Yabo", "value": "Yabo"}
    ],
    'Taraba': [
        {"label": "Ardo-Kola", "value": "Ardo-Kola"}, {"label": "Bali", "value": "Bali"}, {"label": "Donga", "value": "Donga"}, {"label": "Gashaka", "value": "Gashaka"}, {"label": "Gassol", "value": "Gassol"}, {"label": "Ibi", "value": "Ibi"}, {"label": "Jalingo", "value": "Jalingo"}, {"label": "Karim-Lamido", "value": "Karim-Lamido"}, {"label": "Kurmi", "value": "Kurmi"}, {"label": "Lau", "value": "Lau"}, {"label": "Oilingo", "value": "Oilingo"}, {"label": "Sardauna", "value": "Sardauna"}, {"label": "Takum", "value": "Takum"}, {"label": "Ussa", "value": "Ussa"}, {"label": "Wukari", "value": "Wukari"}, {"label": "Yorro", "value": "Yorro"}, {"label": "Zing", "value": "Zing"}
    ],
    'Yobe': [
        {"label": "Bade", "value": "Bade"}, {"label": "Borsali", "value": "Borsali"}, {"label": "Damaturu", "value": "Damaturu"}, {"label": "Fika", "value": "Fika"}, {"label": "Fune", "value": "Fune"}, {"label": "Geidam", "value": "Geidam"}, {"label": "Gogaram", "value": "Gogaram"}, {"label": "Gujba", "value": "Gujba"}, {"label": "Gulani", "value": "Gulani"}, {"label": "Jakusko", "value": "Jakusko"}, {"label": "Karasuwa", "value": "Karasuwa"}, {"label": "Machina", "value": "Machina"}, {"label": "Nangere", "value": "Nangere"}, {"label": "Nguru", "value": "Nguru"}, {"label": "Potiskum", "value": "Potiskum"}, {"label": "Tarmua", "value": "Tarmua"}, {"label": "Yunusari", "value": "Yunusari"}, {"label": "Yusufari", "value": "Yusufari"}
    ],
    'Zamfara': [
        {"label": "Anka", "value": "Anka"}, {"label": "Bakura", "value": "Bakura"}, {"label": "Bukkuyum", "value": "Bukkuyum"}, {"label": "Bungudu", "value": "Bungudu"}, {"label": "Gumi", "value": "Gumi"}, {"label": "Gusau", "value": "Gusau"}, {"label": "Isa", "value": "Isa"}, {"label": "Kaura-Namoda", "value": "Kaura-Namoda"}, {"label": "Kiyawa", "value": "Kiyawa"}, {"label": "Maradun", "value": "Maradun"}, {"label": "Maru", "value": "Maru"}, {"label": "Shinkafi", "value": "Shinkafi"}, {"label": "Talata-Mafara", "value": "Talata-Mafara"}, {"label": "Tsafe", "value": "Tsafe"}, {"label": "Zurmi", "value": "Zurmi"}
    ]
}