export const state_list = [
    {"label": "Abia", "value": "Abia"},
    {"label": "Adamawa", "value": "Adamawa"},
    {"label": "Akwa Ibom", "value": "Akwa-Ibom"},
    {"label": "Anambra", "value": "Anambra"},
    {"label": "Bauchi", "value": "Bauchi"},
    {"label": "Benue", "value": "Benue"},
    {"label": "Borno", "value": "Borno"},
    {"label": "Bayelsa", "value": "Bayelsa"},
    {"label": "Cross River", "value": "Cross-River"},
    {"label": "Delta", "value": "Delta"},
    {"label": "Ebonyi", "value": "Ebonyi"},
    {"label": "Edo", "value": "Edo"},
    {"label": "Ekiti", "value": "Ekiti"},
    {"label": "Enugu", "value": "Enugu"},
    {"label": "Federal Capital Territory", "value": "FCT"},
    {"label": "Gombe", "value": "Gombe"},
    {"label": "Imo", "value": "Imo"},
    {"label": "Jigawa", "value": "Jigawa"},
    {"label": "Kebbi", "value": "Kebbi"},
    {"label": "Kaduna", "value": "Kaduna"},
    {"label": "Kano", "value": "Kano"},
    {"label": "Kogi", "value": "Kogi"},
    {"label": "Katsina", "value": "Katsina"},
    {"label": "Kwara", "value": "Kwara"},
    {"label": "Lagos", "value": "Lagos"},
    {"label": "Nassarawa", "value": "Nassarawa"},
    {"label": "Niger", "value": "Niger"},
    {"label": "Ogun", "value": "Ogun"},
    {"label": "Ondo", "value": "Ondo"},
    {"label": "Osun", "value": "Osun"},
    {"label": "Oyo", "value": "Oyo"},
    {"label": "Plateau", "value": "Plateau"},
    {"label": "Rivers", "value": "Rivers"},
    {"label": "Sokoto", "value": "Sokoto"},
    {"label": "Taraba", "value": "Taraba"},
    {"label": "Yobe", "value": "Yobe"},
    {"label": "Zamfara", "value": "Zamfara"},
]
